# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  release:
    types: [published, edited]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'
  
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: npm version
        run: npm --version
      - name: pack
        run: npm pack
      - shell: bash
        run: ./build.sh
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: pack
          path: tga.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download module download file
        uses: actions/download-artifact@v2
        with:
          name: pack
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Set this to false if you want to prevent updating existing releases
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './pack'
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
    

    
